import { Inter } from 'next/font/google'
import Script from 'next/script';
import './globals.css'
import Sidebar from '@/components/Sidebar,';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script type="text/javascript" src="//cdn.datacamp.com/dcl-react.js.gz"></Script>
      <body className={inter.className + "h-screen flex flex-row justify-start"}>
        <Sidebar/>
        <div className='flex-1 p-4'>{children}</div>
      </body>
    </html>
  )
}
